### PR TITLE
Enable Links

### PR DESCRIPTION
**Pull request by jsonpreet**
Demo: https://xmtp-inbox-web-teal.vercel.app/

Enable links in messages.

### CODE REVIEW

**Comment by bhavya2611** [comment]
@jsonpreet I see you added stuff for emojis too, but that does not work, can you look into it

**Comment by jsonpreet** [comment]
> @jsonpreet I see you added stuff for emojis too, but that does not work, can you look into it

Sure let me check, it should convert and render emojis

**Comment by jsonpreet** [comment]
Hi @bhavya2611 it's fixed can you please check

**Comment by bhavya2611** [comment]
Hey, I tried to test this again -> I still don't see emojis

image

**Comment by jsonpreet** [comment]
> Hey, I tried to test this again -> I still don't see emojis
> 
> image

I tried with :cyclone: shortcode and it's worked for me. Can you please tell me which type of emoji are you trying? It's from emoji picker or manual shortcode?

**Comment by bhavya2611** [comment]
> I tried with 🌀 cyclone shortcode and it's worked for me. Can you please tell me which type of emoji are you trying? It's from emoji picker or manual shortcode?

I tried to send Hey :D

**Comment by bhavya2611** [comment]
Okay if I send

New Msg :D -> does not work

If I send only 

:D - it works but still shows that unresolved img dom

@jsonpreet

**Comment by jsonpreet** [comment]
@bhavya2611 it seems the issue is fixed.

image

**Comment by bhavya2611** [comment]
@jsonpreet can you please give me access to raise a PR on your repo, add some minor tweaks one we merge them we can merge this PR to our repo :D

**Comment by jsonpreet** [comment]
> @jsonpreet can you please give me access to raise a PR on your repo, add some minor tweaks one we merge them we can merge this PR to our repo :D

Invitation Sent Sir.

**Comment by bhavya2611** [comment]
> Invitation Sent Sir.

Raised a PR please check

**Comment by jsonpreet** [comment]
> 
> 
> > Invitation Sent Sir.
> 
> 
> 
> Raised a PR please check

Done Ser

**Review by bhavya2611 — APPROVED** [review]
LG

**Pull request merged**
