### PR TITLE
Update prettier config and apply it

### PR DESCRIPTION
**Pull request by rygine**
To provide a good developer experience and reduce the friction of adoption, we should make our code bases consistent and universal. To this end, we use Prettier to ensure all code is formatted in the same way; however, we should consider some changes to our current configuration to make it more consistent and universally approachable.

# Proposed solution

Outside of some changes to the current config, default values have been explicitly added for options in case they ever change.

```json
{
  "arrowParens": "always",
  "bracketSameLine": true,
  "bracketSpacing": true,
  "embeddedLanguageFormatting": "auto",
  "endOfLine": "lf",
  "htmlWhitespaceSensitivity": "css",
  "jsxSingleQuote": false,
  "printWidth": 80,
  "proseWrap": "preserve",
  "quoteProps": "as-needed",
  "semi": true,
  "singleAttributePerLine": false,
  "singleQuote": false,
  "tabWidth": 2,
  "trailingComma": "all",
  "useTabs": false
}
```

### **bracketSameLine: `false` ⇒ `true`**

This will transition this

```xml
<button
  className="prettier-class"
  id="prettier-id"
  onClick={handleClick}
>
  Click Here
</button>
```

to this

```xml
<button
  className="prettier-class"
  id="prettier-id"
  onClick={handleClick}>
  Click Here
</button>
```

This change minimizes the number of lines of code while maintaining readability.

### **printWidth: `110` ⇒ `80`**

`80` characters is still the universally accepted line length for code. It’s easier to read and the most compatible with all code editors. Prettier also recommends this value.

### **trailingCommas: `none` ⇒ `all`**

Ensuring that trailing commas are always present creates cleaner git diffs and removes  annoyances related to adding/sorting object keys/values.

### **singleQuote: `true` ⇒ `false`**

This may be the most controversial change, and can be a very personal stylistic choice; however, there are a few compelling reasons to switch to double quotes.

- Single quotes are also apostrophes, which can create ambiguity of intent
- Most languages use double quotes, which makes it a more universal choice
- JSON requires double quotes, which makes everything more consistent

### CODE REVIEW

**Comment by neekolas** [comment]
What do we think about removing semicolons while we are at it? `xmtp-js` is already semicolon free

**Comment by neekolas** [comment]
I think all the other proposed changes are a net positive

**Comment by rygine** [comment]
> What do we think about removing semicolons while we are at it? xmtp-js is already semicolon free.

i'm against removing them. having to remember the rules around javascript's automatic semicolon insertion is just one 1 more thing to have to deal with on top of all the other joys of javascript. yes, i know that `prettier` will assist here and in some cases [add semicolons to the beginning of a line](https://prettier.io/docs/en/rationale.html#semicolons) to ensure things work, but that seems to defeat the purpose of no semicolons and looks confusing.

IMO, semicolons in javascript have been an accepted convention for a long time and most of the tutorials, articles, and documentation i read on a regular basis include them. i think the explicit use of semicolons creates more clarity in code. one of the most powerful aspects of javascript is its flexibility, but that also comes with an assortment of footguns. while no semicolons shouldn't be a big deal for experienced developers, it may hinder those with less experience.

**Comment by bhavya2611** [comment]
@rygine can you please resolve the conflict rest looks good

**Review by bhavya2611 — APPROVED** [review]

**Pull request merged**
