### PR TITLE
Fix/connect issue

### LINKED ISSUE #46: Bug: Wallet disconnects upon page refresh
## Describe the bug

After Eleanor has successfully connected her wallet to xmtp.chat, her wallet is disconnected if she refreshes the page and she must connect it once again

## Steps to Reproduce

1. Go to xmtp.chat
2. Connect wallet
3. Refresh page
4. Observe wallet is no longer connected

## Expected behavior

Wallet stays connected when I refresh the page

## Screenshots

Added a screen recording

### Desktop

Please complete the following information if you think it is relevant to the bug:

Chrome 109.0.5414.87

### Smartphone

Please complete the following information if you think it is relevant to the bug:

- Device: [e.g. iPhone 14]
- OS: [e.g. iOS 16.1]
- Browser: [e.g. Safari, Chrome]

### PR DESCRIPTION
**Pull request by bhavya2611**
Fixes #46

### CODE REVIEW

**Review by elisealix22 — COMMENTED** [review]
I can't test currently because of a missing infura ID in the WalletConnect flow. Could this possibly be related? Happy to retest when it's resolved though!

**Comment by m-005** [comment]
Same error as @elisealix22 on dev and prod preview links when clicking the "WalletConnect" option in the modal

**Review by m-005 — APPROVED** [review]
LGTM.

**Review by daria-github — APPROVED** [review]
Fixes 1 issue but regresses another; discussed offline that we'll bring this topic up to the larger team to evaluate tradeoffs. Merging in meantime

**Pull request merged**
